---
- import_playbook: playbooks/preflight.yml
- import_playbook: playbooks/os.yml
- import_playbook: playbooks/rke2.yml
- import_playbook: playbooks/rancher.yml
- import_playbook: playbooks/validation.yml
