---
- name: Recoger estado Kubernetes
  ansible.builtin.import_tasks: cluster.yml

- name: Validar datastore etcd
  ansible.builtin.import_tasks: etcd.yml

- name: Validar Rancher y cert-manager
  ansible.builtin.import_tasks: rancher.yml

- name: Validar conectividad post-deploy
  ansible.builtin.import_tasks: network.yml

- name: Validar servicios funcionales del clúster
  ansible.builtin.import_tasks: functional.yml

- name: Evaluar plataforma
  ansible.builtin.import_tasks: evaluate.yml

- name: Generar evidencias e informe
  ansible.builtin.import_tasks: report.yml

- name: Aplicar resultado de validación
  ansible.builtin.import_tasks: enforce.yml
