---
- name: Asegurar curl instalado
  ansible.builtin.package:
    name: curl
    state: present

- name: Desactivar swap activa
  ansible.builtin.command:
    cmd: swapoff -a
  when: ansible_swaptotal_mb | int > 0
  changed_when: true

- name: Detectar fstab
  ansible.builtin.stat:
    path: /etc/fstab
  register: fstab_file

- name: Desactivar swap persistente en fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^(?!#)(.*\sswap\s.*)$'
    replace: '# \1'
  when: fstab_file.stat.exists

- name: Configurar módulos requeridos
  ansible.builtin.copy:
    dest: /etc/modules-load.d/rke2.conf
    mode: "0644"
    content: |
      overlay
      br_netfilter

- name: Cargar módulos del kernel
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Configurar parámetros de red del kernel
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/90-rke2.conf
    sysctl_set: true
    reload: false
  loop:
    - name: net.bridge.bridge-nf-call-iptables
      value: "1"
    - name: net.bridge.bridge-nf-call-ip6tables
      value: "1"
    - name: net.ipv4.ip_forward
      value: "1"
