---
- name: Comprobar binario RKE2
  ansible.builtin.stat:
    path: /usr/local/bin/rke2
  register: status_rke2_binary

- name: Obtener versión RKE2
  ansible.builtin.command:
    cmd: /usr/local/bin/rke2 --version
  register: status_rke2_version_command
  changed_when: false
  failed_when: false
  when: status_rke2_binary.stat.exists

- name: Extraer versión RKE2
  ansible.builtin.set_fact:
    status_rke2_version: >-
      {{
        status_rke2_version_command.stdout
        | default('')
        | regex_search('rke2 version ([^ ]+)', '\\1')
        | default([], true)
        | first
        | default('unknown')
      }}
